/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/VanGogh/个人/Blog/local/node_modules/@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/VanGogh/个人/Blog/local/node_modules/@vuepress/plugin-active-header-links/clientRootMixin.js"
import m2 from "/Users/VanGogh/个人/Blog/local/node_modules/@vuepress/plugin-nprogress/clientRootMixin.js"
import m3 from "/Users/VanGogh/个人/Blog/local/node_modules/@vuepress/plugin-medium-zoom/clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]