/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/VanGogh/个人/Blog/local/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-77807f17",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77807f17").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-086845c4",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-086845c4").then(next)
    },
  },
  {
    name: "v-ac5d273c",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac5d273c").then(next)
    },
  },
  {
    name: "v-13a477b2",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13a477b2").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-36e61346",
    path: "/en/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36e61346").then(next)
    },
  },
  {
    name: "v-31b9eef8",
    path: "/en/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31b9eef8").then(next)
    },
  },
  {
    name: "v-179abd72",
    path: "/en/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-179abd72").then(next)
    },
  },
  {
    path: "/en/faq/index.html",
    redirect: "/en/faq/"
  },
  {
    name: "v-f01a5d72",
    path: "/en/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f01a5d72").then(next)
    },
  },
  {
    path: "/en/guide/index.html",
    redirect: "/en/guide/"
  },
  {
    name: "v-00222a64",
    path: "/en/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00222a64").then(next)
    },
  },
  {
    name: "v-37296ab8",
    path: "/en/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37296ab8").then(next)
    },
  },
  {
    name: "v-0d33fce4",
    path: "/en/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d33fce4").then(next)
    },
  },
  {
    name: "v-f4286bc8",
    path: "/en/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f4286bc8").then(next)
    },
  },
  {
    name: "v-7054dbae",
    path: "/en/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7054dbae").then(next)
    },
  },
  {
    name: "v-d80bdfdc",
    path: "/en/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d80bdfdc").then(next)
    },
  },
  {
    name: "v-53fc9558",
    path: "/en/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53fc9558").then(next)
    },
  },
  {
    name: "v-72c0e1f8",
    path: "/en/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72c0e1f8").then(next)
    },
  },
  {
    name: "v-ac1222ec",
    path: "/en/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac1222ec").then(next)
    },
  },
  {
    name: "v-70518ce4",
    path: "/en/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70518ce4").then(next)
    },
  },
  {
    name: "v-03baf7f8",
    path: "/en/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03baf7f8").then(next)
    },
  },
  {
    name: "v-50117e70",
    path: "/en/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50117e70").then(next)
    },
  },
  {
    name: "v-21ead4ac",
    path: "/en/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21ead4ac").then(next)
    },
  },
  {
    name: "v-a033c078",
    path: "/en/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a033c078").then(next)
    },
  },
  {
    name: "v-47f69a38",
    path: "/en/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47f69a38").then(next)
    },
  },
  {
    name: "v-17612c83",
    path: "/en/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17612c83").then(next)
    },
  },
  {
    path: "/en/plugin/index.html",
    redirect: "/en/plugin/"
  },
  {
    name: "v-21929db8",
    path: "/en/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21929db8").then(next)
    },
  },
  {
    name: "v-67c1d2fa",
    path: "/en/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67c1d2fa").then(next)
    },
  },
  {
    name: "v-564efd38",
    path: "/en/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-564efd38").then(next)
    },
  },
  {
    name: "v-05111f44",
    path: "/en/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05111f44").then(next)
    },
  },
  {
    name: "v-2c835894",
    path: "/en/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c835894").then(next)
    },
  },
  {
    name: "v-82ced120",
    path: "/en/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82ced120").then(next)
    },
  },
  {
    name: "v-7b33e5f8",
    path: "/en/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b33e5f8").then(next)
    },
  },
  {
    name: "v-5b1011c4",
    path: "/en/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b1011c4").then(next)
    },
  },
  {
    name: "v-509093b8",
    path: "/en/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-509093b8").then(next)
    },
  },
  {
    name: "v-7f48ad64",
    path: "/en/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f48ad64").then(next)
    },
  },
  {
    name: "v-0ab91028",
    path: "/en/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ab91028").then(next)
    },
  },
  {
    name: "v-553b97d4",
    path: "/en/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-553b97d4").then(next)
    },
  },
  {
    name: "v-37616704",
    path: "/en/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37616704").then(next)
    },
  },
  {
    name: "v-19b5c267",
    path: "/en/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19b5c267").then(next)
    },
  },
  {
    path: "/en/theme/index.html",
    redirect: "/en/theme/"
  },
  {
    name: "v-2003e714",
    path: "/en/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2003e714").then(next)
    },
  },
  {
    name: "v-40621aa4",
    path: "/en/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40621aa4").then(next)
    },
  },
  {
    name: "v-512d2200",
    path: "/en/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-512d2200").then(next)
    },
  },
  {
    name: "v-59372360",
    path: "/en/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59372360").then(next)
    },
  },
  {
    name: "v-231f5409",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-231f5409").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-477f61fd",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-477f61fd").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-42e33664",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42e33664").then(next)
    },
  },
  {
    name: "v-0b3e14e8",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b3e14e8").then(next)
    },
  },
  {
    name: "v-5f5b009c",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f5b009c").then(next)
    },
  },
  {
    name: "v-89544438",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89544438").then(next)
    },
  },
  {
    name: "v-9da1fcf8",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9da1fcf8").then(next)
    },
  },
  {
    name: "v-7f25dc44",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f25dc44").then(next)
    },
  },
  {
    name: "v-5bf75b64",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bf75b64").then(next)
    },
  },
  {
    name: "v-956475a4",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-956475a4").then(next)
    },
  },
  {
    name: "v-1f476504",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f476504").then(next)
    },
  },
  {
    name: "v-0efa268c",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0efa268c").then(next)
    },
  },
  {
    name: "v-93b5e74c",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93b5e74c").then(next)
    },
  },
  {
    name: "v-5ad1d124",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ad1d124").then(next)
    },
  },
  {
    name: "v-4a135678",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a135678").then(next)
    },
  },
  {
    name: "v-a48983dc",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a48983dc").then(next)
    },
  },
  {
    name: "v-0c8f0464",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c8f0464").then(next)
    },
  },
  {
    name: "v-69a8b090",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69a8b090").then(next)
    },
  },
  {
    name: "v-236ff6e7",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-236ff6e7").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-5e008544",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e008544").then(next)
    },
  },
  {
    name: "v-4341bcb4",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4341bcb4").then(next)
    },
  },
  {
    name: "v-1272a21e",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1272a21e").then(next)
    },
  },
  {
    name: "v-f5235938",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f5235938").then(next)
    },
  },
  {
    name: "v-624531bc",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-624531bc").then(next)
    },
  },
  {
    name: "v-81585004",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81585004").then(next)
    },
  },
  {
    name: "v-db9bd8b8",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db9bd8b8").then(next)
    },
  },
  {
    name: "v-71395374",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71395374").then(next)
    },
  },
  {
    name: "v-a2930800",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2930800").then(next)
    },
  },
  {
    name: "v-278f70a4",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-278f70a4").then(next)
    },
  },
  {
    name: "v-2a7199a3",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a7199a3").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-4b07d064",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b07d064").then(next)
    },
  },
  {
    name: "v-b6797938",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6797938").then(next)
    },
  },
  {
    name: "v-317f6f64",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-317f6f64").then(next)
    },
  },
  {
    name: "v-862ff980",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-862ff980").then(next)
    },
  },
  {
    name: "v-a48092b8",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a48092b8").then(next)
    },
  },
  {
    name: "v-cf1055b8",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf1055b8").then(next)
    },
  },
  {
    name: "v-31113307",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31113307").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-41ddf5a5",
    path: "/en/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41ddf5a5").then(next)
    },
  },
  {
    path: "/en/config/index.html",
    redirect: "/en/config/"
  },
  {
    name: "v-a9371340",
    path: "/en/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9371340").then(next)
    },
  },
  {
    name: "v-d1410fb8",
    path: "/en/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1410fb8").then(next)
    },
  },
  {
    name: "v-4be87324",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4be87324").then(next)
    },
  },
  {
    name: "v-4f6db820",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f6db820").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]