/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/mnt/e/Blog/local/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-67465e4c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67465e4c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5a2877aa",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a2877aa").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-7ac4fc3f",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ac4fc3f").then(next)
    },
  },
  {
    name: "v-9c6fae3e",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c6fae3e").then(next)
    },
  },
  {
    name: "v-6f85584a",
    path: "/en/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f85584a").then(next)
    },
  },
  {
    path: "/en/guide/index.html",
    redirect: "/en/guide/"
  },
  {
    name: "v-76cf21ca",
    path: "/en/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76cf21ca").then(next)
    },
  },
  {
    path: "/en/faq/index.html",
    redirect: "/en/faq/"
  },
  {
    name: "v-62cb98fe",
    path: "/en/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62cb98fe").then(next)
    },
  },
  {
    name: "v-48a7f3fe",
    path: "/en/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48a7f3fe").then(next)
    },
  },
  {
    name: "v-062978f9",
    path: "/en/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-062978f9").then(next)
    },
  },
  {
    name: "v-70fde48b",
    path: "/en/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70fde48b").then(next)
    },
  },
  {
    name: "v-03a22822",
    path: "/en/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03a22822").then(next)
    },
  },
  {
    name: "v-40369131",
    path: "/en/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40369131").then(next)
    },
  },
  {
    name: "v-e5caa2be",
    path: "/en/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5caa2be").then(next)
    },
  },
  {
    name: "v-41a46ca3",
    path: "/en/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41a46ca3").then(next)
    },
  },
  {
    name: "v-08422021",
    path: "/en/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08422021").then(next)
    },
  },
  {
    name: "v-799480fe",
    path: "/en/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-799480fe").then(next)
    },
  },
  {
    name: "v-02994025",
    path: "/en/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02994025").then(next)
    },
  },
  {
    name: "v-64ce1787",
    path: "/en/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64ce1787").then(next)
    },
  },
  {
    name: "v-5ef59041",
    path: "/en/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ef59041").then(next)
    },
  },
  {
    name: "v-51c834c1",
    path: "/en/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51c834c1").then(next)
    },
  },
  {
    name: "v-646dfec6",
    path: "/en/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-646dfec6").then(next)
    },
  },
  {
    path: "/en/plugin/index.html",
    redirect: "/en/plugin/"
  },
  {
    name: "v-69c0f6c1",
    path: "/en/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69c0f6c1").then(next)
    },
  },
  {
    name: "v-686adbd7",
    path: "/en/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-686adbd7").then(next)
    },
  },
  {
    name: "v-2a95b0e1",
    path: "/en/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a95b0e1").then(next)
    },
  },
  {
    name: "v-21483901",
    path: "/en/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21483901").then(next)
    },
  },
  {
    name: "v-3bb07ea1",
    path: "/en/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bb07ea1").then(next)
    },
  },
  {
    name: "v-a9f37e32",
    path: "/en/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9f37e32").then(next)
    },
  },
  {
    name: "v-3da00c3e",
    path: "/en/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3da00c3e").then(next)
    },
  },
  {
    name: "v-d5819466",
    path: "/en/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5819466").then(next)
    },
  },
  {
    name: "v-3f4521c1",
    path: "/en/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f4521c1").then(next)
    },
  },
  {
    name: "v-ff06dbf6",
    path: "/en/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff06dbf6").then(next)
    },
  },
  {
    name: "v-688f35fe",
    path: "/en/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-688f35fe").then(next)
    },
  },
  {
    name: "v-302ac2be",
    path: "/en/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-302ac2be").then(next)
    },
  },
  {
    name: "v-811f189e",
    path: "/en/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-811f189e").then(next)
    },
  },
  {
    name: "v-0148496a",
    path: "/en/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0148496a").then(next)
    },
  },
  {
    path: "/en/theme/index.html",
    redirect: "/en/theme/"
  },
  {
    name: "v-fc49e73e",
    path: "/en/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc49e73e").then(next)
    },
  },
  {
    name: "v-4f0e7d46",
    path: "/en/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f0e7d46").then(next)
    },
  },
  {
    name: "v-60537861",
    path: "/en/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60537861").then(next)
    },
  },
  {
    name: "v-3d994a2d",
    path: "/en/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d994a2d").then(next)
    },
  },
  {
    name: "v-733b32cc",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-733b32cc").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-ac28cd7e",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac28cd7e").then(next)
    },
  },
  {
    name: "v-35e01445",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35e01445").then(next)
    },
  },
  {
    name: "v-55382740",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55382740").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-6bc33681",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bc33681").then(next)
    },
  },
  {
    name: "v-7339390e",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7339390e").then(next)
    },
  },
  {
    name: "v-52fcbdfe",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52fcbdfe").then(next)
    },
  },
  {
    name: "v-0c9fbc3e",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c9fbc3e").then(next)
    },
  },
  {
    name: "v-04133421",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04133421").then(next)
    },
  },
  {
    name: "v-29670121",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29670121").then(next)
    },
  },
  {
    name: "v-7fe7c2ea",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fe7c2ea").then(next)
    },
  },
  {
    name: "v-72817b92",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72817b92").then(next)
    },
  },
  {
    name: "v-232bd2e9",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-232bd2e9").then(next)
    },
  },
  {
    name: "v-2949da41",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2949da41").then(next)
    },
  },
  {
    name: "v-4283c061",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4283c061").then(next)
    },
  },
  {
    name: "v-a26adf22",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a26adf22").then(next)
    },
  },
  {
    name: "v-b3e7112c",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3e7112c").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-741c7001",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-741c7001").then(next)
    },
  },
  {
    name: "v-d76aa026",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d76aa026").then(next)
    },
  },
  {
    name: "v-2d46ae11",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d46ae11").then(next)
    },
  },
  {
    name: "v-5dba9b02",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dba9b02").then(next)
    },
  },
  {
    name: "v-9e36903e",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e36903e").then(next)
    },
  },
  {
    name: "v-1851fbc1",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1851fbc1").then(next)
    },
  },
  {
    name: "v-4ce6ce81",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ce6ce81").then(next)
    },
  },
  {
    name: "v-14b7ed7b",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b7ed7b").then(next)
    },
  },
  {
    name: "v-351759db",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-351759db").then(next)
    },
  },
  {
    name: "v-5b3e44d1",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b3e44d1").then(next)
    },
  },
  {
    name: "v-0d9fbd46",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d9fbd46").then(next)
    },
  },
  {
    name: "v-e1c6477e",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e1c6477e").then(next)
    },
  },
  {
    name: "v-1f4d8901",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f4d8901").then(next)
    },
  },
  {
    name: "v-458bff81",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-458bff81").then(next)
    },
  },
  {
    name: "v-382a5ee6",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-382a5ee6").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-f738bbfe",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f738bbfe").then(next)
    },
  },
  {
    name: "v-64fb8dc6",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64fb8dc6").then(next)
    },
  },
  {
    name: "v-90415a7e",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-90415a7e").then(next)
    },
  },
  {
    name: "v-13021ac1",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13021ac1").then(next)
    },
  },
  {
    name: "v-20aceff1",
    path: "/en/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20aceff1").then(next)
    },
  },
  {
    name: "v-168849f1",
    path: "/en/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-168849f1").then(next)
    },
  },
  {
    name: "v-4a81b6c1",
    path: "/en/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a81b6c1").then(next)
    },
  },
  {
    name: "v-98a498ec",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98a498ec").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-e22a7030",
    path: "/en/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e22a7030").then(next)
    },
  },
  {
    path: "/en/config/index.html",
    redirect: "/en/config/"
  },
  {
    name: "v-a7e50186",
    path: "/en/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7e50186").then(next)
    },
  },
  {
    name: "v-0226387e",
    path: "/en/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0226387e").then(next)
    },
  },
  {
    name: "v-c266b47e",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c266b47e").then(next)
    },
  },
  {
    name: "v-cc314506",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc314506").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]